docs_dir: mkdocs
site_dir: docs
site_name: Yaml
theme: 'material'
pages:
    - Install: index.md
    - Read: read.md
    - Write/Update: write.md
    - Create: create.md
    - Convert: convert.md
    - Merge: merge.md
repo_name: 'mikefarah/yaml'
repo_url: 'https://github.com/mikefarah/yaml'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/mikefarah'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/mike-farah-b5a75b2/'

markdown_extensions:
  - markdown_include.include:
      base_path: mkdocs
  - toc(permalink=true)